apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-openclaw
resources:
  - openclaw-sealed-secret.yaml
  - resources/namespace.yaml
  - resources/configmap.yaml
  - resources/pvc.yaml
  - resources/service.yaml
  - resources/deployment.yaml
  - resources/httproute.yaml
