apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trafficserver

resources:
  - resources/namespace.yaml
  - resources/certificate.yaml
  - resources/configmap.yaml
  - resources/pvc.yaml
  - resources/deployment.yaml
  - resources/service.yaml

transformers:
  - ../../image-prefix.yaml
