apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildkitd
resources:
  - resources/certificate.yaml
  - resources/configmap.yaml
  - resources/deployment.yaml
  - resources/namespace.yaml
  - resources/service.yaml
# Normalize DockerHub images by adding docker.io registry
images:
  - name: moby/buildkit
    newName: docker.io/moby/buildkit
transformers:
  - ../../image-prefix.yaml
