apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
- resources/namespace.yaml
- resources/gitlab-runner-sealedsecret.yaml
helmCharts:
# - name: gitlab-agent
#   repo: https://charts.gitlab.io
#   version: 2.23.0
#   includeCRDs: true
#   releaseName: gitlab-agent
#   valuesFile: values/gitlab-agent-2.23.0.yaml
#   namespace: gitlab
- name: gitlab-runner
  repo: https://charts.gitlab.io
  version: 0.85.0
  includeCRDs: true
  releaseName: gitlab-runner
  valuesFile: values/gitlab-runner-0.85.0.yaml
  namespace: gitlab
transformers:
  - ../../image-prefix.yaml
