# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-gzctf

helmGlobals:
  chartHome: charts/gzctf-helm

helmCharts:
  - name: gzctf
    releaseName: gzctf
    namespace: dev-gzctf
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - gzctf-sealed-secret.yaml
  - postgresql-ha-postgresql-sealed-secret.yaml
  - postgresql-ha-pgpool-sealed-secret.yaml
