apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: # metal3 currently do not support installing into a specific namespace
resources:
- https://github.com/metal3-io/ironic-standalone-operator/releases/download/v0.8.0/install.yaml
- resources/sealedsecret-bmc.yaml
- bmo
helmCharts:
- name: cluster
  includeCRDs: true
  releaseName: cluster
  namespace: zjusct
  valuesFile: values/cluster.yaml
transformers:
  - ../../image-prefix.yaml
