{{- if .Values.ipa.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ipa.secrets.name }}
type: Opaque
data:
  {{ .Values.ipa.secrets.adminPasswordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{ .Values.ipa.secrets.directoryPasswordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
