apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- resources/namespace.yaml
- resources/sealedsecret.yaml
- resources/clusterissuers.yaml
- resources/referencegrant.yaml
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  includeCRDs: true
  releaseName: cert-manager
  valuesFile: values/cert-manager-v1.19.3.yaml
  namespace: cert-manager
  version: v1.19.3
transformers:
  - ../../image-prefix.yaml
