apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server
resources:
- resources/namespace.yaml
helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server/
  includeCRDs: true
  releaseName: metrics-server
  version: 3.13.0
  namespace: metrics-server
  valuesFile: values/metrics-server-3.13.0.yaml
transformers:
  - ../../image-prefix.yaml
