apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly
resources:
- resources/namespace.yaml
helmCharts:
- name: dragonfly
  repo: https://dragonflyoss.github.io/helm-charts/
  includeCRDs: true
  releaseName: dragonfly
  valuesFile: values/dragonfly-1.6.13.yaml
  version: 1.6.13
  namespace: dragonfly
transformers:
  - ../../image-prefix.yaml
