apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- resources/namespace.yaml
helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  includeCRDs: true
  releaseName: ingress-nginx
  valuesFile: values/ingress-nginx-4.14.3.yaml
  version: 4.14.3
  namespace: ingress-nginx
transformers:
  - ../../image-prefix.yaml
