---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgC14YtMn+eN8RGtAfLZEEVIQkvN0r0IUyg1KHsk1qsjZO8SEM310jSwPihi4SxlJUu+mPAjlvVtVASKyseC9Zi83NicBWd7946keegdLzyvE8ojxcDt2njr+/+tPKpz72C3Lo+fENwaV+5MwziTHbbwvfnre4hc60aOK9X4w3rlRbVVVClRSWtOdIxRF4N32yhIc7xQabBohp3An6pMv7ooz3dxp0WT7vpqbYfkOxu6+L18Y8kfnJyuJcyPB0jouEJwz3iSysnVMgZStsiA6QJrMZTY08IAtPxGfXyfb/Os3b8Yo1+BdAi0Q18ENeIxuaq2sKeFRUy5Kl+kzsC6FUk0qMNIeamKn3HPtQEBUE5/WzgsZfI3kZ2GeOvYYOgmdlsPn/Fpx4MDVgcZr6pBuKog9+Kjiojf/A/dXBMKqFt+xqVU9m04wzUpSMwroKTEvF+4nZjhFWR5OFkPsKpmICWJYOiWfJNwSba0PDRgvPtS3J/ehBwHPxz2dVKSbPWLo1q4LPObne+/82Nj2KjQmuTWoeUJLcKwelySasqQE7c5ON4HbA9tDqZExXY9vLxLG7fa+PPp7OuZgVSQdcXpgqtd9h/Y116RDFc5VAyowdAOsrChKJIsvq+kdNnZH3yLORJq9Yg51YOoQShsFwZypA+hhJDHRGRvy7MyD6Ys2Gk9cqThuTXRHQx1BSh28SOOWiPl62Xi7Y4wycptcDL9bQ==
    admin-user: AgCSD7HmRKCsRWktXO83tNvOfH+PHIXwpFGITLorqRzWtbM87Gt37bD0c4JwzSEflRXhipyeV9YyIgOTnIB3eEBAedGG4DzjhcJ0aHUYrTxSpQX5k+WJG+rN5P4Ra9+KVV7kkJ4ZGKe/coLBa2+jwACzDTT8OAoauZ2J5Fw2P/d6ca/CgR4Xmm7QGmoMVCNWZabzkeFytW9UT/alfpR1IBXeiYUzMHrvYjKQeEEOXZnzwSjCsLf4bJzoeyQdL5SNl1tsi3EPCAzSi7SHXWrG1ESRxUvQy6Nnvbuz1yXXGLoMb8GJADUwVOQVa6BmvCjofiYprslcqKoZLJgEn1tAQXm0Q1Q5fRm1zcGiuR7pHSVUFWzA6u3jsMddeKAm9uagRTFu0+BFdco6iTzYMsDYsrogwsLh4k0s2d6Ms+Ng76Wg9hkba+BonKVNJOsb4VC2r+qYHZurojNjUSKdePrCZoysmSjSTHJDrxdo/Ep8AGwb8CX1MWYluBLsZ5Nes9CDRyq5vDpUySRHRD+moK8/EkMz1SRDfJyJmCeCAAJSub3KsJRFGLB49RFVkQd3PjQVa4iz7rKqJG05nctPrjb2I3gPOYlR3+FIbT+tM4II+UiD0YX7pfky+0wsGRTvjsxqyfTRTSLtE6TQmytJoCHSof70/uGkLUbkV3AivBKA9wsNzgD0/RfCn98i245kGtblGMEeT31qPg==
  template:
    metadata:
      name: grafana-secrets
      namespace: kube-prometheus-stack
    type: Opaque
