apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
- resources/namespace.yaml
- resources/admin-password.yaml
helmCharts:
- name: jenkins
  repo: https://charts.jenkins.io
  includeCRDs: true
  releaseName: jenkins
  valuesFile: values/jenkins-5.8.139.yaml
  version: 5.8.139
  namespace: jenkins
