# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitwarden

resources:
  - sealedsecret.yaml
  - namespace.yaml

helmCharts:
  - name: self-host
    repo: https://charts.bitwarden.com
    releaseName: self-host
    namespace: bitwarden
    valuesFile: values.yaml
    includeCRDs: true
  # - name: sm-operator
  #   repo: https://charts.bitwarden.com
  #   releaseName: sm-operator
  #   namespace: key
  #   valuesFile: values.yaml
  #   includeCRDs: true
